### ISSUE TITLE
Error in series lookup

### ISSUE THREAD

**Issue by tholzheim** [tholzheim/orapi#10]
Selecting certain series leads to an error on the Series overview page.

Reason: Error in lookup function to get the events of a series
https://github.com/WolfgangFahl/ConferenceCorpus/blob/727afb6f5c9b2e3807260a6161a27531b2f77dd2/corpus/event.py#L489
uses two different lookup tables to get the series one is by acronym and one by pageTitle due to the missing acronym issue both tables deviate causing a lookup error

**Comment by WolfgangFahl** [comment]
Isn't this a bug in the OpenResearch Website? Alexander Gesinn pointed out the same issue yesterday - the form doesn't use the lookup either which should be by isA Event Series and return the page
