### ISSUE TITLE
Publish series does not publish series

### ISSUE THREAD

**Issue by WolfgangFahl** [tholzheim/orapi#19]
[ICADL.xlsx](https://github.com/tholzheim/orapi/files/7678224/ICADL.xlsx)

created new items but these were not uploaded to orclone. 
see https://confident.dbis.rwth-aachen.de/or/index.php?title=ICADL

**Comment by WolfgangFahl** [comment]
![grafik](https://user-images.githubusercontent.com/1336221/145266482-c0a92496-66d1-4732-a468-31b5507c9aac.png)

**Comment by WolfgangFahl** [comment]
the dblp column is also no updated ..

**Comment by tholzheim** [comment]
The dblpIds were added to the WikiSON but not set by the template.
There was a typo in Template:Event `{{{dblpConferenceId}}}` instead of `{{{DblpConferenceId}}}`.
Is fixed now.

For new Events the seriesLookup of the EventManager seems not to be updated when adding a new Event to the Manager.
