### ISSUE TITLE
date handling e.g. conversion to ISO-Dates

### ISSUE THREAD

**Issue by WolfgangFahl** [tholzheim/orapi#35]
- https://confident.dbis.rwth-aachen.de/or/index.php?title=ICSE
- https://confident.dbis.rwth-aachen.de/orapi/api/series/ICSE?source=orclone 

is an example for a conference series with dates that need some love.
It would be good if the date enhancing would be a standard enhancing feature to make sure the dates show up properly in
the spreadsheet.

E.g.

- 23/04/1995 -> 1995-04-23
- 4/06/2000 -> 2000-06-04
- 2021/05/22 -> 2021-05-22

**Comment by tholzheim** [comment]
closed with #37
