### ISSUE TITLE
Excel support

### ISSUE THREAD

**Issue by WolfgangFahl** [tholzheim/orapi#7]
This is a method for creating excel compatible output ... Could we implement that?
```python
df=pd.DataFrame(lod)
writer = pd.ExcelWriter(f'{eventSeriesAcronym}.xlsx', engine='xlsxwriter')
df.to_excel(writer, index = False)
writer.save()
```

**Comment by tholzheim** [comment]
Looks promising the read and write over pandas data frames seems easier than the current approach.
```python
pd.read_excel(open('tmp.xlsx', 'rb'),sheet_name='Sheet3')  
```
But the customization of the generated document is more restricted. None the less this should be the better solution for this usecase
